server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: FRIzhdd_3269
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.service_haidian.bean
